[package]
name = "virtual-path-db"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
redb = "3.1.0"
rkyv = "0.8.12"
thiserror.workspace = true

[lints]
workspace = true
